[features]
seeds = false

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

## /target is excluded from being pushed so upon cloning and 
## running anchor build and then anchor deploy
## newly created program addresses have to be pasted below
## as well as into respective programs and then need to run 
## anchor build and then anchor deploy
## AGAIN

[programs.localnet]
example1 = "3JZbrbicNUWvxRPBWoMfyL3fvPv63UtCL45pZuqND3oq" 
example2 = "6NFEJ9qaX3CTRHDxD7nETJYSRq9emLNQJ4o4D1xyMJfc"
example3 = "F6SL4uZqqgaeorbx8dAuiRsKavzdqx1d87xxZ6yngpHn"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test1 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/test_example_lottery.ts"
test2 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/test_example_rps.ts"
test3 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/test_example_consortium.ts"

